version: '3.1'

services:
  app:
    image: java-21-openjdk-amd64
    command: javadoc -sourcepath src -cp /ourclasses/ -d mydocumentation -subpackages ru
    volumes:
      - ./bin:/ourclasses
      - ./src:/src
      - ./doc:/mydocumentation
